### ISSUE TITLE
Issue when starting controller with cozmo

### ISSUE THREAD

**Issue by JohnMackYouTube05** [remotv/controller#22]
When I fire up remo controller on Windows, I get this error from python:
p_build_version=00003.00004.00000
2020-02-29 15:03:19,037 cozmo.general INFO     Found robot id=1
2020-02-29 15:03:19,039 cozmo.general INFO     Connected to iOS device_id=1 serial=d8ce66a1a256da38b0f1b35e72046c9452a466f2
2020-02-29 15:03:19,269 cozmo.general INFO     Robot id=1 serial=02e11d84 initialized OK
not coz
15:03:19 - controller.py : Unhandled exception of type : <class 'ModuleNotFoundError'>
Traceback (most recent call last):
  File "controller.py", line 356, in <module>
    video_module = importlib.import_module('video.'+commandArgs.video)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'video.cozmo'

Please help, I want to get this working.

Also, I can't figure out how to use cozmo's integrated camera as a video device, and cozmo_tts doesn't fully work.

**Comment by sybergoosejr** [comment]
what phone/device are you using for cozmo? i have gotten a similar error in the past when my pc could not get photos from my phone due to the phone did not have trust with the pc yet.

**Comment by JohnMackYouTube05** [comment]
I realized it was cause I put "cozmo" as the video type, but that's not correct.

**Comment by TGCFabian** [comment]
For using cozmo, you need to use "cozmo_vid" for video, and cozmo for controller, then it should work all fine, no need for webcams

**Comment by JohnMackYouTube05** [comment]
So it would be camera_device="cozmo_vid"?

**Comment by TGCFabian** [comment]
no, it should be "type=cozmo_vid" instead of type=ffmpeg

For tts use tts=cozmo_tts

**Comment by TGCFabian** [comment]
All settings should be

At line 20
`type=cozmo`

At line 31
`no_mic=true`
Unless you have a good mic

At line 38
`type=cozmo_vid`

and at line 119
`tts=cozmo_tts`

That should be all
