### ISSUE TITLE
Add info for Anki Vector in the Wiki.

### ISSUE THREAD

**Issue by JohnMackYouTube05** [remotv/controller#26]
I was trying to get my Anki Vector up and streaming on Remo, and it looks like the controller files already have python files for vector in every category! 
In the /video folder...
![image](https://user-images.githubusercontent.com/16242045/77584441-ca90ad00-6eb0-11ea-865b-83e1cb9d11c3.png)
In the TTS folder...
![image](https://user-images.githubusercontent.com/16242045/77584467-d7150580-6eb0-11ea-8847-b94f6b4790ff.png)
and even in the hardware folder!
![image](https://user-images.githubusercontent.com/16242045/77584489-e300c780-6eb0-11ea-98e4-b7a4efb8488d.png)

Problem is when I use those parameters in controller.conf, it still thinks I want to stream a Cozmo, (probably because the new vector robot controller, is a duplicate copy of my original cozmo controller folder) even though I set everything to vector stuff. (e.g. type=vector under robot, tts=vector_tts under tts, and type=vector_vid under camera)

Please help

**Comment by bwookieeeee** [comment]
My understanding is that Vector is not yet ready to stream to Remo, and documentation will not be provided until it can successfully and reliably stream to the platform.

**Comment by JohnMackYouTube05** [comment]
To add to the issue, closed or not, (please don't ban me for this) it also throws this when I try opening up the controller python script,
```
C:\Users\liljm\Downloads\remocontroller\controller-master-vector>python -m controller.py
18:38:46 - controller.py : RemoTV Controller Starting up
'sudo' is not recognized as an internal or external command,
operable program or batch file.
'sudo' is not recognized as an internal or external command,
operable program or batch file.
18:38:47.741          robot.AsyncRobot WARNING  No serial number or name provided. Automatically selecting 003073fe
18:38:47.762     connection.Connection    INFO  Connecting to 10.0.0.242:443 for Vector-N4J9 using C:\Users\liljm\.anki_vector\Vector-N4J9-003073fe.cert
18:38:48.896     connection.Connection    INFO  BehaviorControl control_granted_response { }
18:38:50 - controller.py : Unhandled exception of type : <class 'configparser.NoOptionError'>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 789, in get
    value = d[option]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\collections\__init__.py", line 891, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\collections\__init__.py", line 883, in __missing__
    raise KeyError(key)
KeyError: 'x_res'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\liljm\Downloads\remocontroller\controller-master-vector\controller.py", line 341, in <module>
    module.setup(robot_config)
  File "C:\Users\liljm\Downloads\remocontroller\controller-master-vector\hardware\vector.py", line 63, in setup
    x_res = robot_config.getint('camera', 'x_res')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'x_res' in section: 'camera'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 437, in result
    raise CancelledError()
concurrent.futures._base.CancelledError
Future exception was never retrieved
future: <Future finished exception=StopAsyncIteration()>
Traceback (most recent call last):
  File "C:\Users\liljm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\aiogrpc\utils.py", line 126, in _next
    return next(self._iterator)
  File "C:\Users\liljm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\grpc\_channel.py", line 416, in __next__
    return self._next()
  File "C:\Users\liljm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\grpc\_channel.py", line 704, in _next
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\liljm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\aiogrpc\utils.py", line 128, in _next
    raise StopAsyncIteration
StopAsyncIteration
```
